[msg ModMenuName]
[s]Amicitia Mod Menu[w][e]

[msg AboutMsg[About this menu]]
[s]Created by [clr 1]DniweTamp[clr 0] using TGE's[n][clr 9]AtlusScriptCompiler[clr 0] tool.[w][e]

[sel ModMenu]
[s]Use original square function[e]
[s]Player[e]
[s]Battle Select[e]
[s]Sound Test[e]
[s]Field Select[e]
[s]Next Page[e]
[s]Cancel[e]

[sel ModMenu2]
[s]Event Select[e]
[s]Flags[e]
[s]Font Test[e]
[s]About[e]
[s]Previous Page[e]
[s]Cancel[e]

[sel PlayerMenu]
[s]Personas[e]
[s]Social Stats[e]
[s]Items[e]
[s]Set Confidant Rank[e]
[s]Set Protagonist Name[e]
[s]Max Money[e]
[s]Cancel[e]

[sel PersonaMenu]
[s]Add Persona[e]
[s]Delete Personas[e]
[s]Add Skill[e]
[s]Unlock Full Compendium[e]
[s]Evolve Persona[e]
[s]Cancel[e]

[msg PersonaAddPrompt [Add Persona]]
[s]Input the ID of the Persona to add.[n](max. 3 digits)[w][e]

[msg SkillPrompt [Add Skill]]
[s]Enter the ID of the skill to add.[n](max. 3 digits)[w][e]

[sel UnitSelect]
[s]Protagonist[e]
[s]Yukari[e]
[s]Aigis[e]
[s]Mitsuru[e]
[s]Junpei[e]
[s]Fuuka[e]
[s]Akihiko[e]
[s]Ken[e]
[s]Shinjiro[e]
[s]Koromaru[e]

[msg MoneyAdded]
[s]You recieved [clr 1]99999999[clr 0] yen.[w][e]

[sel BattleTypeMenu]
[s]Regular Encounter[e]
[s]Cancel[e]

[msg EncounterPrompt]
[s]Set the number of the encounter[n]you want to fight (max. 3 digits).[w][e]

[sel FieldSelect]
[s]Quick Travel Select[e]
[s]Enter Field ID[e]
[s]Load Field ID[e]
[s]Cancel[e]

[sel ShortcutSelect]
[s]School Shortcuts[e]
[s]Dorm Shortcuts[e]
[s]Station Shortcuts[e]
[s]Kyoto Shortcuts[e]
[s]Cancel[e]

[sel EventSelect]
[s]Enter Event ID[e]
[s]Load Event ID[e]
[s]Cancel[e]

[msg FontTest[The Font Guy]]
[s]ABCDEFGHIJKLMNOPQRSTUVWXYZ[n]abcdefghijklmnopqrstuvwxyz[n][w][e]
[s]1234567890-_.:,;|!"#$%&/[n]()=?+*{}^\<>`~'@[w][e]

[msg FieldDlg [Field Select]]
[s]Choose the first 3 digits of[n]the field to load.[n][w][e]

[msg FieldDlg2 [Field Select]]
[s]Choose the last 3 digits of[n]the field to load.[n][w][e]

[msg EventDlg [Event Select]]
[s]Choose the first 3 digits of[n]the event to load.[n][w][e]

[msg EventDlg2 [Event Select]]
[s]Choose the last 3 digits of[n]the event to load.[n][w][e]

[sel FlagMenu]
[s]Add Party Members[e]
[s]Remove Party Members[e]
[s]Enable Party Editing[e]
[s]Manual Input[e]
[s]Mass Flag Editor[e]
[s]Cancel[e]

[msg FlagCheckOn]
[s]The flag is on.[w][e]

[msg FlagCheckOff]
[s]The flag is off.[w][e]

[sel FlagMassEditor]
[s]Disable all flags[e]
[s]Enable all flags[e]
[s]Swap enabled/disabled flags[e]
[s]Cancel[e]

[msg LoadCheckError]
[s]Set the required parameters[n]before attempting to load![w][e]

[msg NotImplemented]
[s]This feature is currently not implemented.[n][w][e]

[msg MSGDummy]
[s][w][e]