[msg ModMenuName]
[s]Amicitia Mod Menu[w][e]

[msg AboutMsg[About this menu]]
[s]Created by [clr 1]DniweTamp[clr 0] using TGE's[n][clr 9]AtlusScriptCompiler[clr 0] tool.[w][e]

[sel ModMenu]
[s]Use original square function[e]
[s]Battle Select[e]
[s]Sound Test[e]
[s]Field Select[e]
[s]Event Select[e]
[s]Next Page[e]
[s]Cancel[e]

[sel ModMenu2]
[s]Flags[e]
[s]Font Test[e]
[s]About[e]
[s]Previous Page[e]
[s]Cancel[e]

[sel FieldSelect]
[s]Quick Travel Select[e]
[s]Enter Field ID[e]
[s]Load Field ID[e]
[s]Cancel[e]

[sel ShortcutSelect]
[s]School Shortcuts[e]
[s]Dorm Shortcuts[e]
[s]Station Shortcuts[e]
[s]Kyoto Shortcuts[e]
[s]Cancel[e]

[sel EventSelect]
[s]Enter Event ID[e]
[s]Load Event ID[e]
[s]Cancel[e]

[msg FontTest[The Font Guy]]
[s]ABCDEFGHIJKLMNOPQRSTUVWXYZ[n]abcdefghijklmnopqrstuvwxyz[n][w][e]
[s]1234567890-_.:,;|!"#$%&/[n]()=?+*{}^\<>`~'@[w][e]

[msg NotImplemented]
[s]This feature is currently not implemented.[n][w][e]

[msg EventDlg [Event Select]]
[s]Choose the first 3 digits of[n]the event to load.[n][w][e]

[msg EventDlg2 [Event Select]]
[s]Choose the last 3 digits of[n]the event to load.[n][w][e]

[msg LoadCheckError]
[s]Set the required parameters[n]before attempting to load![w][e]

[msg MSGDummy]
[s][w][e]