del *.flow
set NLM=^


set NL=^^^%NLM%%NLM%^%NLM%%NLM%

echo import( "../original/h06_01.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f006_001_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	school_shortcut();%NL%} > h06_01.flow
echo import( "../original/h06_02.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f006_002_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	school_shortcut();%NL%} > h06_02.flow
echo import( "../original/h06_03.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f006_003_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	school_shortcut();%NL%} > h06_03.flow
echo import( "../original/h06_04.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f006_004_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	school_shortcut();%NL%} > h06_04.flow
echo import( "../original/h06_05.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f006_005_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	school_shortcut();%NL%} > h06_05.flow
echo import( "../original/h06_07.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f006_007_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	school_shortcut();%NL%} > h06_07.flow
echo import( "../original/h06_11.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f006_011_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	school_shortcut();%NL%} > h06_11.flow
echo import( "../original/h06_16.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f006_016_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	school_shortcut();%NL%} > h06_16.flow
echo import( "../original/h06_20.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f006_020_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	school_shortcut();%NL%} > h06_20.flow
echo import( "../original/h07_01.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f007_001_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	dormitory_shortcut();%NL%} > h07_01.flow
echo import( "../original/h07_02.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f007_002_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	dormitory_shortcut();%NL%} > h07_02.flow
echo import( "../original/h07_03.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f007_003_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	dormitory_shortcut();%NL%} > h07_03.flow
echo import( "../original/h07_04.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f007_004_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	dormitory_shortcut();%NL%} > h07_04.flow
echo import( "../original/h07_05.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f007_005_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	dormitory_shortcut();%NL%} > h07_05.flow
echo import( "../original/h07_06.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f007_006_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	dormitory_shortcut();%NL%} > h07_06.flow
echo import( "../original/h07_09.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f007_009_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	FUNCTION_002C( 14, 2 );%NL%	int var2 = MSG_SELECT( 116, 115, 0 );%NL%	%NL%	if ( ( var2 == 0 ) )%NL%	{%NL%		HIT_SCRIPT_01();%NL%	}%NL%	else if ( ( var2 == 1 ) )%NL%	{%NL%		HIT_SCRIPT_00();%NL%	}%NL%	else %NL%	{%NL%		MSG_WND_CLS();%NL%		return;%NL%	}%NL%%NL%} > h07_09.flow
echo import( "../original/h07_19.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f007_019_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	dormitory_shortcut();%NL%} > h07_19.flow
echo import( "../original/h07_20.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f007_020_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	dormitory_shortcut();%NL%} > h07_20.flow
echo import( "../original/h08_01.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f008_001_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	int var11 = 7;%NL%	FUNCTION_002C( 14, 5 );%NL%	int var12 = MSG_SELECT( 37, 36, var11 );%NL%	%NL%	if ( ( var12 == 0 ) )%NL%	{%NL%		HIT_SCRIPT_04();%NL%	}%NL%	else if ( ( var12 == 1 ) )%NL%	{%NL%		HIT_SCRIPT_08();%NL%	}%NL%	else if ( ( var12 == 2 ) )%NL%	{%NL%		HIT_SCRIPT_07();%NL%	}%NL%	else if ( ( var12 == 3 ) )%NL%	{%NL%		HIT_SCRIPT_05();%NL%	}%NL%	else if ( ( var12 == 4 ) )%NL%	{%NL%		HIT_SCRIPT_00();%NL%	}%NL%	else %NL%	{%NL%		MSG_WND_CLS();%NL%		return;%NL%	}%NL%%NL%} > h08_01.flow
echo import( "../original/h08_02.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f008_002_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	int var0 = 0;%NL%	FUNCTION_002C( 14, 1 );%NL%	int var1 = MSG_SELECT( 2, 1, var0 );%NL%	%NL%	if ( ( var1 == 0 ) )%NL%	{%NL%		HIT_SCRIPT_00();%NL%	}%NL%	else %NL%	{%NL%		MSG_WND_CLS();%NL%		return;%NL%	}%NL%%NL%} > h08_02.flow
echo import( "../original/h08_09.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f008_009_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	FUNCTION_002C( 14, 2 );%NL%	int var0 = MSG_SELECT( 2, 1, 0 );%NL%	%NL%	if ( ( var0 == 0 ) )%NL%	{%NL%		HIT_SCRIPT_00();%NL%		return;%NL%	}%NL%	else if ( ( var0 == 1 ) )%NL%	{%NL%		BIT_ON( ( ( ( 0 + 0x0400 ) + 0x0800 ) + 19 ) );%NL%		FADE( 3, 20 );%NL%		CLD_FUNCTION_0003( 1 );%NL%		return;%NL%	}%NL%	else %NL%	{%NL%		MSG_WND_CLS();%NL%		return;%NL%	}%NL%%NL%} > h08_09.flow
echo import( "../original/h08_10.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f008_010_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	FUNCTION_002C( 14, 2 );%NL%	int var0 = MSG_SELECT( 3, 2, 0 );%NL%	%NL%	if ( ( var0 == 0 ) )%NL%	{%NL%		HIT_SCRIPT_01();%NL%		return;%NL%	}%NL%	else if ( ( var0 == 1 ) )%NL%	{%NL%		BIT_ON( ( ( ( 0 + 0x0400 ) + 0x0800 ) + 19 ) );%NL%		FADE( 3, 20 );%NL%		CLD_FUNCTION_0003( 1 );%NL%		return;%NL%	}%NL%	else %NL%	{%NL%		MSG_WND_CLS();%NL%		return;%NL%	}%NL%%NL%} > h08_10.flow
echo import( "../original/h09_01.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f009_001_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	int var5 = 0;%NL%	FUNCTION_002C( 14, 3 );%NL%	int var6 = MSG_SELECT( 22, 21, var5 );%NL%	%NL%	if ( ( var6 == 0 ) )%NL%	{%NL%		HIT_SCRIPT_01();%NL%	}%NL%	else if ( ( var6 == 1 ) )%NL%	{%NL%		HIT_SCRIPT_05();%NL%	}%NL%	else if ( ( var6 == 2 ) )%NL%	{%NL%		HIT_SCRIPT_00();%NL%	}%NL%	else %NL%	{%NL%		MSG_WND_CLS();%NL%		return;%NL%	}%NL%%NL%} > h09_01.flow
echo import( "../original/h09_02.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f009_002_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	int var3 = 0;%NL%	FUNCTION_002C( 14, 2 );%NL%	int var4 = MSG_SELECT( 9, 8, var3 );%NL%	%NL%	if ( ( var4 == 0 ) )%NL%	{%NL%		HIT_SCRIPT_00();%NL%	}%NL%	else if ( ( var4 == 1 ) )%NL%	{%NL%		HIT_SCRIPT_01();%NL%	}%NL%	else %NL%	{%NL%		MSG_WND_CLS();%NL%		return;%NL%	}%NL%%NL%} > h09_02.flow
echo import( "../original/h09_08.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f009_008_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	int var3 = 0;%NL%	FUNCTION_002C( 14, 3 );%NL%	int var4 = MSG_SELECT( 17, 0x10, var3 );%NL%	%NL%	if ( ( var4 == 0 ) )%NL%	{%NL%		FADE( 3, 20 );%NL%		CALL_FIELD( 9, 2, 0, 0 );%NL%		return;%NL%	}%NL%	else if ( ( var4 == 1 ) )%NL%	{%NL%		HIT_SCRIPT_00();%NL%	}%NL%	else if ( ( var4 == 2 ) )%NL%	{%NL%		BIT_ON( ( ( ( 0 + 0x0400 ) + 0x0800 ) + 18 ) );%NL%		FADE( 3, 20 );%NL%		FUNCTION_000F();%NL%		CLD_FUNCTION_0003( 3 );%NL%		return;%NL%	}%NL%	else %NL%	{%NL%		MSG_WND_CLS();%NL%		return;%NL%	}%NL%%NL%} > h09_08.flow
echo import( "../original/h09_09.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f009_009_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	FUNCTION_002C( 14, 1 );%NL%	int var6 = MSG_SELECT( 13, 12, 0 );%NL%	%NL%	if ( ( var6 == 0 ) )%NL%	{%NL%		HIT_SCRIPT_01();%NL%	}%NL%	else %NL%	{%NL%		MSG_WND_CLS();%NL%		return;%NL%	}%NL%%NL%} > h09_09.flow
echo import( "../original/h10_01.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f010_001_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	station_shortcut();%NL%} > h10_01.flow
echo import( "../original/h10_02.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f010_002_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	station_shortcut();%NL%} > h10_02.flow
echo import( "../original/h12_01.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f012_001_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	int var15 = 0;%NL%	FUNCTION_002C( 14, 1 );%NL%	int var16 = MSG_SELECT( 53, 52, var15 );%NL%	%NL%	if ( ( var16 == 0 ) )%NL%	{%NL%		HIT_SCRIPT_00();%NL%	}%NL%	else %NL%	{%NL%		MSG_WND_CLS();%NL%		return;%NL%	}%NL%%NL%} > h12_01.flow
echo import( "../original/h14_02.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f014_002_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	kyoto_shortcut();%NL%} > h14_02.flow
echo import( "../original/h14_03.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f014_003_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	kyoto_shortcut();%NL%} > h14_03.flow
echo import( "../original/h14_06.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f014_006_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	kyoto_shortcut();%NL%} > h14_06.flow
echo import( "../original/h14_07.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f014_007_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	kyoto_shortcut();%NL%} > h14_07.flow
echo import( "../original/h14_08.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f014_008_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	kyoto_shortcut();%NL%} > h14_08.flow
echo import( "../original/h14_09.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f014_009_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	kyoto_shortcut();%NL%} > h14_09.flow
echo import( "../original/h14_10.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f014_010_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	kyoto_shortcut();%NL%} > h14_10.flow
echo import( "../original/h14_11.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f014_011_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	kyoto_shortcut();%NL%} > h14_11.flow
echo import( "../original/h14_12.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f014_012_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	kyoto_shortcut();%NL%} > h14_12.flow
echo import( "../original/h14_13.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f014_013_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	kyoto_shortcut();%NL%} > h14_13.flow
echo import( "../original/h14_14.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f014_014_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	kyoto_shortcut();%NL%} > h14_14.flow
echo import( "../original/h14_15.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f014_015_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	kyoto_shortcut();%NL%} > h14_15.flow
echo import( "../original/h14_16.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f014_016_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	kyoto_shortcut();%NL%} > h14_16.flow
echo import( "../original/h15_18.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f015_018_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	int var55 = 0;%NL%	%NL%	if ( !BIT_CHK( ( ( ( 0 + 0x0400 ) + 0x0800 ) + 301 ) ) )%NL%	{%NL%		var55 = 4;%NL%	}%NL%	else %NL%	{%NL%		var55 = 0;%NL%	}%NL%%NL%	FUNCTION_002C( 14, 4 );%NL%	int var56 = MSG_SELECT( 73, 72, var55 );%NL%	%NL%	if ( ( var56 == 0 ) )%NL%	{%NL%		HIT_SCRIPT_03();%NL%	}%NL%	else if ( ( var56 == 1 ) )%NL%	{%NL%		HIT_SCRIPT_02();%NL%	}%NL%	else if ( ( var56 == 2 ) )%NL%	{%NL%		HIT_SCRIPT_01();%NL%	}%NL%	else if ( ( var56 == 3 ) )%NL%	{%NL%		HIT_SCRIPT_00();%NL%	}%NL%	else %NL%	{%NL%		MSG_WND_CLS();%NL%		return;%NL%	}%NL%%NL%} > h15_18.flow
echo import( "../original/h35_03.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f035_003_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	FUNCTION_002C( 14, 2 );%NL%	int var0 = MSG_SELECT( 3, 2, 0 );%NL%	%NL%	if ( ( var0 == 0 ) )%NL%	{%NL%		HIT_SCRIPT_00();%NL%	}%NL%	else if ( ( var0 == 1 ) )%NL%	{%NL%		HIT_SCRIPT_01();%NL%	}%NL%	else %NL%	{%NL%		MSG_WND_CLS();%NL%		return;%NL%	}%NL%%NL%} > h35_03.flow
echo import( "../original/h37_02.bf" );%NL%import( "../ModMenu.flow" );%NL%%NL%void f037_002_shortcut_hook()%NL%{%NL%	ModMenuInit();%NL%}%NL%%NL%void CallOriginalSquareMenu()%NL%{%NL%	FUNCTION_002C( 14, 1 );%NL%	int var1 = MSG_SELECT( 6, 5, 0 );%NL%	%NL%	if ( ( var1 == 0 ) )%NL%	{%NL%		HIT_SCRIPT_00();%NL%	}%NL%	else %NL%	{%NL%		MSG_WND_CLS();%NL%		return;%NL%	}%NL%%NL%} > h37_02.flow